name: npm test
on:
  workflow_dispatch:

jobs:
  call-test-workflow:
    - name: Call test workflow
      run: mickael-spilmont-hm/sfeir-github-action/.github/workflows/ex4.yaml@main
      with:
        node_version: '14'
    - name: Check Node version
      run: node -v
