name: Switch Node version
on:
  pull_request:

env:
  NODE_VERSION: 14

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ env.node_version }}
        - name: run test
          shell: bash
          run: |
            npm install
            npm test
        - name: Check node version
          run: node -v
