name: interact with Github API
on:
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set SHA7 variable
        run: echo "SHA_7=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Controle variable
        run: echo $SHA_7
